In [33]:
import pandas as pd

In [34]:
##question 1: pandas version

In [35]:
pd.__version__

'3.0.6'

In [36]:
##Question2: n of rows of df

In [37]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-26 11:48:02--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.2’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.007s

2026-09-26 11:48:02 (82.4 MB/s) - ‘car_fuel_efficiency_2026.csv.2’ saved [635180/635180]

In [38]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

In [39]:
df = pd.read_csv(url)

In [40]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [41]:
df.index.max()

9999

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [43]:
df.shape[0]

10000

In [44]:
##question3: fuel types

In [45]:
df.fuel_type.nunique()

3

In [46]:
##question 4: missing values

In [66]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [48]:
##Question5: Max fuel efficiency from Asia

In [49]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(41.2)

In [50]:
##Question 6:Median value of horsepower

In [60]:
median_before = df.horsepower.median()
median_before

np.float64(254.0)

In [62]:
mode = df.horsepower.mode()[0]
mode

np.float64(252.0)

In [63]:
df['horsepower'] = df['horsepower'].fillna(mode)

In [64]:
median_after = df.horsepower.median()
median_after

np.float64(252.0)

In [65]:
df['horsepower'].isnull().sum()

np.int64(0)

In [67]:
##Q7: Sum of weights

In [70]:
df_asia = df[df['origin'] == 'Asia']
df_asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [72]:
df_asia = df_asia[['vehicle_weight', 'model_year']]
df_asia

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [74]:
df_asia.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [76]:
x = df_asia.head(7).values
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [78]:
xT = x.T
xT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [85]:
XTX = xT.dot(x)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [86]:
import numpy as np

In [88]:
XTXi = np.linalg.inv(XTX)
XTXi

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [89]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [90]:
w = XTXi.dot(xT).dot(y)
w

array([0.13644777, 0.2327492 ])

In [91]:
result = w[0] + w[1]
result

np.float64(0.36919696904925486)